In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/raid_storage/fyaronsky/ruCoIR/results/results.csv')
df

,Unnamed: 0,Qwen/Qwen3-Embedding-0.6B,Qwen/Qwen3-Embedding-4B,Qwen/Qwen3-Embedding-8B,fyaronskiy/code_retriever_ru_en,fyaronskiy/code_retriever_ru_en_512,fyaronskiy/code_retriever_ru_en_256,fyaronskiy/code_retriever_ru_en_128,fyaronskiy/code_retriever_ru_en_64
0,apps.,0.82420,0.92906,0.93252,0.13504,0.12783,0.11855,0.10712,0.07100
1,codefeedback-st.,0.92171,0.96204,0.97687,0.81083,0.80391,0.78686,0.76273,0.70254
2,stackoverflow-qa.,0.91019,0.95474,0.96097,0.81192,0.80323,0.79713,0.76834,0.71944
3,cosqa.,0.41885,0.48151,0.47824,0.25464,0.24394,0.24070,0.20943,0.18714
4,CodeSearchNet-go.,0.85627,0.93391,0.92184,0.76006,0.75306,0.74463,0.73605,0.66926
5,CodeSearchNet-java.,0.83726,0.91208,0.90933,0.74042,0.74036,0.72715,0.71305,0.66606
6,CodeSearchNet-javascript.,0.77867,0.83153,0.84329,0.56581,0.56451,0.53970,0.51723,0.47112
7,CodeSearchNet-ruby.,0.90007,0.94924,0.94424,0.79990,0.80322,0.79158,0.74385,0.72137
8,CodeSearchNet-python.,0.84108,0.91513,0.87154,0.90852,0.90199,0.89911,0.87930,0.84402
9,CodeSearchNet-php.,0.89685,0.93594,0.93772,0.82843,0.82582,0.81664,0.79503,0.74801

In [3]:
# Создаем строку со средними
new_row = {'Unnamed: 0': 'Mean'}
for col in df.columns[1:]:
    new_row[col] = df[col].mean()

# Добавляем в DataFrame
df.loc[len(df)] = new_row

df

,Unnamed: 0,Qwen/Qwen3-Embedding-0.6B,Qwen/Qwen3-Embedding-4B,Qwen/Qwen3-Embedding-8B,fyaronskiy/code_retriever_ru_en,fyaronskiy/code_retriever_ru_en_512,fyaronskiy/code_retriever_ru_en_256,fyaronskiy/code_retriever_ru_en_128,fyaronskiy/code_retriever_ru_en_64
0,apps.,0.824200,0.929060,0.932520,0.135040,0.127830,0.118550,0.107120,0.071000
1,codefeedback-st.,0.921710,0.962040,0.976870,0.810830,0.803910,0.786860,0.762730,0.702540
2,stackoverflow-qa.,0.910190,0.954740,0.960970,0.811920,0.803230,0.797130,0.768340,0.719440
3,cosqa.,0.418850,0.481510,0.478240,0.254640,0.243940,0.240700,0.209430,0.187140
4,CodeSearchNet-go.,0.856270,0.933910,0.921840,0.760060,0.753060,0.744630,0.736050,0.669260
5,CodeSearchNet-java.,0.837260,0.912080,0.909330,0.740420,0.740360,0.727150,0.713050,0.666060
6,CodeSearchNet-javascript.,0.778670,0.831530,0.843290,0.565810,0.564510,0.539700,0.517230,0.471120
7,CodeSearchNet-ruby.,0.900070,0.949240,0.944240,0.799900,0.803220,0.791580,0.743850,0.721370
8,CodeSearchNet-python.,0.841080,0.915130,0.871540,0.908520,0.901990,0.899110,0.879300,0.844020
9,CodeSearchNet-php.,0.896850,0.935940,0.937720,0.828430,0.825820,0.816640,0.795030,0.748010
10,Mean,0.818515,0.880518,0.877656,0.661557,0.656787,0.646205,0.623213,0.579996